name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if different

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-minify-plugin

      - name: Build and Deploy to GitHub Pages
        run: mkdocs gh-deploy --force